version: "0.1"

services: 
    frontend:
        build:  
            context: ./frontend
        ports:
            - 8080:80
        volumes:
            - ./frontend:/app
        depends_on:
            - backend
            
    backend:
        build: ./backend
        command: uvicorn app.main:app --reload --workers 1 --host 0.0.0.0 --port 8000
        volumes:
            - ./backend:/usr/src/app
        expose: 
            - 8000
        ports:
            - 8000:8000
        environment:
            - DATABASE_URL=postgresql+asyncpg://postgres:postgres@db:5432/foo
        depends_on:
            - db

    db:
        image: postgres:13.4
        expose:
            - 5432
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
            - POSTGRES_DB=foo
